---
http_interactions:
- request:
    method: post
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:@api-sandbox.bonmarketplace.com.br/product
    body:
      encoding: UTF-8
      string: '{"id":"b2w-ruby-2","name":"B2W Ruby","sku":[{"id":"b2w-ruby-2","name":"B2W
        Ruby","ean":["invalid"],"weight":1,"stockQuantity":3,"enable":true,"price":{"sellPrice":10,"listPrice":10}}],"manufacturer":{"name":"Digital
        Pages","model":"b2w-ruby","warrantyTime":1},"deliveryType":"SHIPMENT","nbm":{"number":"49019900","origin":"1"}}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json;charset=UTF-8
      Content-Length:
      - '327'
      User-Agent:
      - Ruby
  response:
    status:
      code: 422
      message: Unprocessable Entity
    headers:
      Server:
      - nginx/1.7.5
      Date:
      - Mon, 27 Apr 2015 13:43:47 GMT
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '224'
      Connection:
      - keep-alive
      X-Access-Control-Realm:
      - external
    body:
      encoding: UTF-8
      string: '{"httpStatusCode":422,"message":"Nao foi possivel processar as instrucoes
        contidas na requisicao","validationErrors":[{"fieldName":"sku[0].ean","restrictionType":"INVALID","message":"field
        should be a number. Ean:invalid"}]}'
    http_version: 
  recorded_at: Mon, 27 Apr 2015 13:45:34 GMT
recorded_with: VCR 2.9.3
