---
http_interactions:
- request:
    method: post
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:@api-sandbox.bonmarketplace.com.br/product
    body:
      encoding: UTF-8
      string: '{"id":"b2w-ruby-1","name":"B2W Ruby","sku":[{"id":"b2w-ruby-1","name":"B2W
        Ruby","ean":["9789896370107"],"urlImage":["http://imagens.isupply.com.br/436/web/9788539903436.jpg"],"weight":1,"stockQuantity":3,"enable":true,"price":{"sellPrice":10,"listPrice":10}}],"manufacturer":{"name":"Digital
        Pages","model":"b2w-ruby","warrantyTime":1},"deliveryType":"SHIPMENT","nbm":{"number":"49019900","origin":"1"}}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json;charset=UTF-8
      Content-Length:
      - '404'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Server:
      - nginx/1.7.5
      Date:
      - Mon, 27 Apr 2015 13:43:47 GMT
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      X-Access-Control-Realm:
      - external
      Location:
      - https://api-sandbox.bonmarketplace.com.br/product/b2w-ruby-1
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 27 Apr 2015 13:45:34 GMT
recorded_with: VCR 2.9.3
