---
http_interactions:
- request:
    method: post
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:A01D5EA1EE4A33E02C02939F4B0E15D3@api-sandbox.bonmarketplace.com.br/product/invalid/sku
    body:
      encoding: UTF-8
      string: '{"id":"b2w-ruby-1","name":"B2W Ruby","ean":["9789896370107"],"weight":1,"stockQuantity":3,"enable":true,"price":{"sellPrice":10,"listPrice":10}}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json;charset=UTF-8
      Content-Length:
      - '144'
      User-Agent:
      - Ruby
  response:
    status:
      code: 422
      message: Unprocessable Entity
    headers:
      Server:
      - nginx/1.7.5
      Date:
      - Mon, 20 Apr 2015 16:17:40 GMT
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '86'
      Connection:
      - keep-alive
      X-Access-Control-Realm:
      - external
    body:
      encoding: UTF-8
      string: '{"httpStatusCode":422,"message":"ProductId:[invalid] not found","validationErrors":[]}'
    http_version: 
  recorded_at: Mon, 20 Apr 2015 16:19:07 GMT
recorded_with: VCR 2.9.3
