---
http_interactions:
- request:
    method: get
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:@api-sandbox.bonmarketplace.com.br/sku/0123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Server:
      - nginx/1.7.5
      Date:
      - Mon, 27 Apr 2015 13:43:48 GMT
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '57'
      Connection:
      - keep-alive
      X-Access-Control-Realm:
      - external
    body:
      encoding: UTF-8
      string: '{"httpStatusCode":404,"message":"SkuId:[0123] not found"}'
    http_version: 
  recorded_at: Mon, 27 Apr 2015 13:45:35 GMT
recorded_with: VCR 2.9.3
