---
http_interactions:
- request:
    method: get
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:A01D5EA1EE4A33E02C02939F4B0E15D3@api-marketplace.submarino.com.br/v1/sku/b2w-ruby-1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      X-Access-Control-Realm:
      - external
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '313'
      X-N:
      - S
      Date:
      - Mon, 16 Jun 2014 19:23:52 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "{\"id\":\"b2w-ruby-1\",\"name\":\"B2W Ruby\",\"ean\":[\"1234567890128\"],\"height\":1.0,\"width\":0.003333,\"length\":1.0,\"weight\":1.0,\"stockQuantity\":3,\"enable\":true,\"price\":{\"listPrice\":10.0,\"sellPrice\":10.0},\"link\":{\"id\":\"b2w-ruby-1\",\"rel\":\"product\",\"href\":\"https://api-marketplace.submarino.com.br/sandbox/product/b2w-ruby-1\"}}"
    http_version: 
  recorded_at: Mon, 16 Jun 2014 19:23:52 GMT
recorded_with: VCR 2.8.0
