---
http_interactions:
- request:
    method: post
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:A01D5EA1EE4A33E02C02939F4B0E15D3@api-marketplace.submarino.com.br/sandbox/product
    body:
      encoding: UTF-8
      string: "{\"id\":\"b2w-ruby-1\",\"name\":\"B2W Ruby\",\"sku\":[{\"id\":\"b2w-ruby-1\",\"name\":\"B2W
        Ruby\",\"ean\":[\"1234567890128\"],\"weight\":1,\"stockQuantity\":3,\"enable\":true,\"price\":{\"sellPrice\":10,\"listPrice\":10}}],\"manufacturer\":{\"name\":\"Digital
        Pages\",\"model\":\"b2w-ruby\",\"warrantyTime\":1},\"deliveryType\":\"SHIPMENT\",\"nbm\":{\"number\":\"49019900\",\"origin\":\"1\"}}"
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '333'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Server:
      - Apache-Coyote/1.1
      X-Access-Control-Realm:
      - external
      Location:
      - "/product/b2w-ruby-1"
      Content-Type:
      - application/json;charset=UTF-8
      Content-Length:
      - '0'
      Date:
      - Tue, 29 Apr 2014 18:48:35 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 29 Apr 2014 18:48:35 GMT
recorded_with: VCR 2.8.0
