---
http_interactions:
- request:
    method: get
    uri: https://A01D5EA1EE4A33E02C02939F4B0E15D3:A01D5EA1EE4A33E02C02939F4B0E15D3@api-marketplace.submarino.com.br/v1/sku/0123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Server:
      - Apache-Coyote/1.1
      X-Access-Control-Realm:
      - external
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '57'
      Date:
      - Mon, 16 Jun 2014 19:23:52 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "{\"httpStatusCode\":404,\"message\":\"SkuId:[0123] not found\"}"
    http_version: 
  recorded_at: Mon, 16 Jun 2014 19:23:52 GMT
recorded_with: VCR 2.8.0
